# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == 'zeros':
        return np.zeros(shape)
    elif mode == 'ones':
        return np.ones(shape)
    elif mode == 'full':
        if value is None:
            raise ValueError("Value must be specified for 'full' mode")
        return np.full(shape, value)
    elif mode == 'identity':
        # For identity matrix, shape should be a single integer
        if isinstance(shape, (list, tuple)):
            if len(shape) == 1:
                shape = shape[0]
            elif len(shape) == 2:
                if shape[0] != shape[1]:
                    raise ValueError("Identity matrix must be square")
                shape = shape[0]
        return np.identity(shape)
    else:
        raise ValueError(f"Invalid mode: {mode}. Choose from 'zeros', 'ones', 'full', or 'identity'")

In [2]:
# Zeros array
zeros_array = array_factory('zeros', (2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [3]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to NumPy arrays
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Reshape arr1 to new_shape
        reshaped_arr1 = arr1.reshape(new_shape)

        # Vertically stack both datasets
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

In [ ]:
data1 = [1, 2, 3, 4, 5, 6]
data2 = [[7, 8, 9], [10, 11, 12]]

result = secure_reshape_and_stack(data1, data2, (2, 3))

<function secure_reshape_and_stack at 0x0000024AB9F53B00>


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [17]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)
    
    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = arr >= threshold
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

In [18]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# The function call needs to be fixed too
# First reshape branch_a to 2x3, then stack with branch_b
branch_a_reshaped = np.array(branch_a).reshape(2, 3)
branch_b_array = np.array(branch_b)
final_report = np.vstack([branch_a_reshaped, branch_b_array])

In [ ]:
print("Original stacked array:")
print(final_report)
print("\nShape:", final_report.shape)
print("\nAfter applying threshold (>= 8 replaced with -1):")
print(final_report_thresholded)

Original stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape: (4, 3)

After applying threshold (>= 8 replaced with -1):
[[ 1  2  3]
 [ 4  5  6]
 [ 7 -1 -1]
 [-1 -1 -1]]


TestCase

In [16]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 


# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

ValueError: operands could not be broadcast together with shapes (6,) (2,3) 

In [ ]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)
